In [1]:

import sys
from pathlib import Path
from typing import Tuple

import joblib
import numpy as np
from numpy.linalg import inv
import matplotlib.pyplot as plt
import time
import os

# Optional deps used in helper/model stack
import torch  # noqa: F401
import cvxpy as cp  # noqa: F401

# neuromancer symbols are imported in notebook; here they are required indirectly via helper/models loading
from neuromancer.modules import blocks  # type: ignore
from neuromancer.system import Node, System  # type: ignore
from neuromancer.problem import Problem  # type: ignore
from neuromancer.loss import PenaltyLoss  # type: ignore

# Add Identification directory to path for baseline_inference import
identification_path = Path.cwd().resolve().parent / 'Identification'
if str(identification_path) not in sys.path:
    sys.path.append(str(identification_path))
import baseline_inference  # type: ignore

Helper imported succesfully


In [2]:
baseline_inference.init()

Model initialized successfully!
A matrix shape: (35, 35)
B matrix shape: (35, 3)
Scalers loaded for 3 outputs and 3 inputs


In [3]:
scaler = joblib.load(os.path.join('../data', 'scaler.pkl'))

In [4]:
u = np.zeros((3, 1))
baseline_inference.get_x(np.zeros((3, 1)))
for i in range(10000):
    y = baseline_inference.y_plus(u)
print(scaler.inverse_transform(y.reshape(1, -1))[0])

[52.738903 69.24475  53.087387]


In [5]:
u = np.array([[0.0], [1.0], [0.0]])
baseline_inference.get_x(np.zeros((3, 1)))
for i in range(1000):
    y = baseline_inference.y_plus(u)
print(scaler.inverse_transform(y.reshape(1, -1))[0])

[46.915268 56.464188 48.211327]


In [6]:
u = u = np.array([[1.0], [0.0], [0.0]])
baseline_inference.get_x(np.zeros((3, 1)))
for i in range(1000):
    y = baseline_inference.y_plus(u)
print(scaler.inverse_transform(y.reshape(1, -1))[0])

[37.92244 65.88684 38.96766]


In [7]:
u = u = np.array([[0.0], [0.0], [1.0]])
baseline_inference.get_x(np.zeros((3, 1)))
for i in range(1000):
    y = baseline_inference.y_plus(u)
print(scaler.inverse_transform(y.reshape(1, -1))[0])

[64.41976  81.984665 68.14855 ]


In [8]:
u = np.zeros((3, 1))
baseline_inference.get_x(np.zeros((3, 1)))
for i in range(1000):
    y = baseline_inference.y_plus(u)
print(scaler.inverse_transform(y.reshape(1, -1))[0])

[52.73884  69.24463  53.087326]


In [9]:
u = u = np.array([[-.5], [1.5], [1.0]])
baseline_inference.get_x(np.zeros((3, 1)))
for i in range(1000):
    y = baseline_inference.y_plus(u)
print(scaler.inverse_transform(y.reshape(1, -1))[0])

[66.9316  78.9006  75.58253]
