# used steps
time of step 260, numbeer of steps 12 (with starting step)


In [121]:
import numpy as np

In [122]:
u_min = np.array([[30.0, 20.0, 0.0]])
u_max = np.array([[100.0, 100.0, 50.0]])

In [123]:
u_start = np.array([[50.0, 50.0, 20.0]])

In [124]:
steps = 11

random_steps = np.array([np.random.randint(u_min[0], u_max[0] + 1) for _ in range(steps)])

In [125]:
random_steps

array([[ 55,  83,   0],
       [ 71,  62,  12],
       [ 31,  68,   3],
       [ 47,  66,  34],
       [100,  48,  11],
       [ 94,  38,  18],
       [ 55,  46,  32],
       [ 81, 100,  18],
       [ 71,  74,  24],
       [ 55,  43,  19],
       [ 45,  70,  41]])

In [126]:
u_prev = np.zeros(3)
final_values = random_steps.copy()
for i in range(steps):
    final_values[i] = random_steps[i] - u_prev
    u_prev = random_steps[i]

#final_values = np.vstack((u_start, final_values))

final_values


array([[ 55,  83,   0],
       [ 16, -21,  12],
       [-40,   6,  -9],
       [ 16,  -2,  31],
       [ 53, -18, -23],
       [ -6, -10,   7],
       [-39,   8,  14],
       [ 26,  54, -14],
       [-10, -26,   6],
       [-16, -31,  -5],
       [-10,  27,  22]])

In [127]:
np.round(final_values[:,0], 0)

array([ 55,  16, -40,  16,  53,  -6, -39,  26, -10, -16, -10])

In [128]:
np.round(final_values[:,1], 0)

array([ 83, -21,   6,  -2, -18, -10,   8,  54, -26, -31,  27])

In [129]:
np.round(final_values[:,2], 0)

array([  0,  12,  -9,  31, -23,   7,  14, -14,   6,  -5,  22])

In [130]:
print(final_values[:,])

[[ 55  83   0]
 [ 16 -21  12]
 [-40   6  -9]
 [ 16  -2  31]
 [ 53 -18 -23]
 [ -6 -10   7]
 [-39   8  14]
 [ 26  54 -14]
 [-10 -26   6]
 [-16 -31  -5]
 [-10  27  22]]


In [131]:
arr = np.array([260 * (i+1) for i in range(11)])
arr


array([ 260,  520,  780, 1040, 1300, 1560, 1820, 2080, 2340, 2600, 2860])

In [132]:
2860+260


3120