# used steps
time of step 260, numbeer of steps 12 (with starting step)


In [13]:
import numpy as np

In [14]:
u_min = np.array([[30.0, 20.0, 0.0]])
u_max = np.array([[100.0, 100.0, 50.0]])

In [15]:
u_start = np.array([[50.0, 50.0, 20.0]])

In [16]:
steps = 11

random_steps = np.array([np.random.randint(u_min[0], u_max[0] + 1) for _ in range(steps)])

In [17]:
random_steps

array([[48, 56,  0],
       [99, 85, 16],
       [47, 76, 39],
       [34, 53,  6],
       [44, 54, 16],
       [39, 33, 25],
       [98, 97, 38],
       [78, 40,  6],
       [82, 34, 10],
       [85, 49,  8],
       [92, 59, 19]])

In [18]:
u_prev = np.zeros(3)
final_values = random_steps.copy()
for i in range(steps):
    final_values[i] = random_steps[i] - u_prev
    u_prev = random_steps[i]

#final_values = np.vstack((u_start, final_values))

final_values


array([[ 48,  56,   0],
       [ 51,  29,  16],
       [-52,  -9,  23],
       [-13, -23, -33],
       [ 10,   1,  10],
       [ -5, -21,   9],
       [ 59,  64,  13],
       [-20, -57, -32],
       [  4,  -6,   4],
       [  3,  15,  -2],
       [  7,  10,  11]])

In [19]:
np.round(final_values[:,0], 0)

array([ 48,  51, -52, -13,  10,  -5,  59, -20,   4,   3,   7])

In [20]:
np.round(final_values[:,1], 0)

array([ 56,  29,  -9, -23,   1, -21,  64, -57,  -6,  15,  10])

In [21]:
np.round(final_values[:,2], 0)

array([  0,  16,  23, -33,  10,   9,  13, -32,   4,  -2,  11])

In [22]:
print(final_values[:,])

[[ 48  56   0]
 [ 51  29  16]
 [-52  -9  23]
 [-13 -23 -33]
 [ 10   1  10]
 [ -5 -21   9]
 [ 59  64  13]
 [-20 -57 -32]
 [  4  -6   4]
 [  3  15  -2]
 [  7  10  11]]


In [23]:
arr = np.array([260 * (i+1) for i in range(11)])
arr


array([ 260,  520,  780, 1040, 1300, 1560, 1820, 2080, 2340, 2600, 2860])

In [24]:
2860+260


3120