# used steps
time of step 260, numbeer of steps 12 (with starting step)


In [1]:
import numpy as np

In [2]:
u_min = np.array([[30.0, 20.0, 0.0]])
u_max = np.array([[100.0, 100.0, 50.0]])

In [3]:
u_start = np.array([[50.0, 50.0, 20.0]])

In [4]:
steps = 11

random_steps = np.array([np.random.randint(u_min[0], u_max[0] + 1) for _ in range(steps)])

In [5]:
random_steps

array([[88, 30, 45],
       [77, 99, 29],
       [50, 47, 37],
       [56, 98, 18],
       [82, 71, 11],
       [95, 80,  6],
       [48, 75, 32],
       [76, 23, 50],
       [54, 91,  7],
       [80, 82, 48],
       [96, 37, 10]])

In [6]:
u_prev = np.zeros(3)
final_values = random_steps.copy()
for i in range(steps):
    final_values[i] = random_steps[i] - u_prev
    u_prev = random_steps[i]

#final_values = np.vstack((u_start, final_values))

final_values


array([[ 88,  30,  45],
       [-11,  69, -16],
       [-27, -52,   8],
       [  6,  51, -19],
       [ 26, -27,  -7],
       [ 13,   9,  -5],
       [-47,  -5,  26],
       [ 28, -52,  18],
       [-22,  68, -43],
       [ 26,  -9,  41],
       [ 16, -45, -38]])

In [7]:
np.round(final_values[:,0], 0)

array([ 88, -11, -27,   6,  26,  13, -47,  28, -22,  26,  16])

In [8]:
np.round(final_values[:,1], 0)

array([ 30,  69, -52,  51, -27,   9,  -5, -52,  68,  -9, -45])

In [9]:
np.round(final_values[:,2], 0)

array([ 45, -16,   8, -19,  -7,  -5,  26,  18, -43,  41, -38])

In [10]:
print(final_values[:,])

[[ 88  30  45]
 [-11  69 -16]
 [-27 -52   8]
 [  6  51 -19]
 [ 26 -27  -7]
 [ 13   9  -5]
 [-47  -5  26]
 [ 28 -52  18]
 [-22  68 -43]
 [ 26  -9  41]
 [ 16 -45 -38]]


In [11]:
arr = np.array([260 * (i+1) for i in range(11)])
arr


array([ 260,  520,  780, 1040, 1300, 1560, 1820, 2080, 2340, 2600, 2860])

In [12]:
2860+260


3120