# used steps
time of step 260, numbeer of steps 12 (with starting step)


In [541]:
import numpy as np

In [542]:
u_min = np.array([[30.0, 20.0, 0.0]])
u_max = np.array([[100.0, 100.0, 50.0]])

In [543]:
u_start = np.array([[50.0, 50.0, 20.0]])

In [544]:
steps = 11

random_steps = np.array([np.random.randint(u_min[0], u_max[0] + 1) for _ in range(steps)])

In [545]:
random_steps

array([[69, 36,  9],
       [77, 86, 11],
       [85, 98, 30],
       [51, 58,  7],
       [89, 24, 44],
       [65, 38, 19],
       [70, 70, 27],
       [36, 78, 45],
       [90, 42, 44],
       [31, 64, 33],
       [78, 98, 12]])

In [546]:
u_prev = np.zeros(3)
final_values = random_steps.copy()
for i in range(steps):
    final_values[i] = random_steps[i] - u_prev
    u_prev = random_steps[i]

#final_values = np.vstack((u_start, final_values))

final_values


array([[ 69,  36,   9],
       [  8,  50,   2],
       [  8,  12,  19],
       [-34, -40, -23],
       [ 38, -34,  37],
       [-24,  14, -25],
       [  5,  32,   8],
       [-34,   8,  18],
       [ 54, -36,  -1],
       [-59,  22, -11],
       [ 47,  34, -21]])

In [547]:
np.round(final_values[:,0], 0)

array([ 69,   8,   8, -34,  38, -24,   5, -34,  54, -59,  47])

In [548]:
np.round(final_values[:,1], 0)

array([ 36,  50,  12, -40, -34,  14,  32,   8, -36,  22,  34])

In [549]:
np.round(final_values[:,2], 0)

array([  9,   2,  19, -23,  37, -25,   8,  18,  -1, -11, -21])

In [550]:
print(final_values[:,])

[[ 69  36   9]
 [  8  50   2]
 [  8  12  19]
 [-34 -40 -23]
 [ 38 -34  37]
 [-24  14 -25]
 [  5  32   8]
 [-34   8  18]
 [ 54 -36  -1]
 [-59  22 -11]
 [ 47  34 -21]]


In [551]:
arr = np.array([260 * (i+1) for i in range(11)])
arr


array([ 260,  520,  780, 1040, 1300, 1560, 1820, 2080, 2340, 2600, 2860])

In [552]:
2860+260


3120